const records=[
{id:"F-001",type:"fauna",group:"ave",name:"Calandria grande",latin:"Mimus saturninus",status:"documentado",statusLabel:"Registro local",environment:"Zona de chacras y ambientes urbanos",note:"Es una de las aves mencionadas expresamente por el Municipio entre las especies registradas en la zona.",source:"Municipalidad de San Patricio del Chañar",url:"https://sanpatricio.gob.ar/quehacer"},
{id:"F-002",type:"fauna",group:"ave",name:"Carpintero real",latin:"Colaptes melanochloros",status:"documentado",statusLabel:"Registro local",environment:"Arbolado y chacras",note:"El Municipio lo incluye entre las especies destacadas del avistaje local.",source:"Municipalidad de San Patricio del Chañar",url:"https://sanpatricio.gob.ar/quehacer"},
{id:"F-003",type:"fauna",group:"ave",name:"Golondrina patagónica",latin:"Tachycineta leucopyga",status:"documentado",statusLabel:"Registro local",environment:"Cielos abiertos y ambientes ribereños",note:"El Municipio la menciona entre las especies registradas en la zona.",source:"Municipalidad de San Patricio del Chañar",url:"https://sanpatricio.gob.ar/quehacer"},
{id:"F-004",type:"fauna",group:"ave",name:"Cardenal copete rojo",latin:"Paroaria coronata",status:"documentado",statusLabel:"Registro local",environment:"Chacras",note:"19 individuos fueron identificados durante un procedimiento de fauna silvestre realizado en una chacra local en 2018. El dato documenta presencia local, aunque el contexto fue de cautiverio.",source:"Argentina.gob.ar · Gendarmería Nacional",url:"https://www.argentina.gob.ar/noticias/rescatan-en-neuquen-53-aves-silvestres"},
{id:"F-005",type:"fauna",group:"ave",name:"Jilguero",latin:"Carduelis carduelis",status:"documentado",statusLabel:"Registro local",environment:"Chacras",note:"22 individuos fueron identificados en el mismo procedimiento de 2018 en San Patricio del Chañar. Registro asociado a aves en cautiverio.",source:"Argentina.gob.ar · Gendarmería Nacional",url:"https://www.argentina.gob.ar/noticias/rescatan-en-neuquen-53-aves-silvestres"},
{id:"F-006",type:"fauna",group:"ave",name:"Zorzal",latin:"Turdus philomelos",status:"documentado",statusLabel:"Registro local",environment:"Chacras",note:"Cinco individuos fueron identificados en el procedimiento de fauna de 2018. El registro debe leerse en su contexto de cautiverio.",source:"Argentina.gob.ar · Gendarmería Nacional",url:"https://www.argentina.gob.ar/noticias/rescatan-en-neuquen-53-aves-silvestres"},
{id:"F-007",type:"fauna",group:"ave",name:"Pica hueso",latin:"Saltator aurantiirostris",status:"documentado",statusLabel:"Registro local",environment:"Chacras",note:"Un individuo fue identificado en el procedimiento de fauna silvestre de 2018.",source:"Argentina.gob.ar · Gendarmería Nacional",url:"https://www.argentina.gob.ar/noticias/rescatan-en-neuquen-53-aves-silvestres"},
{id:"F-008",type:"fauna",group:"ave",name:"Loica",latin:"Sturnella loyca",status:"documentado",statusLabel:"Registro local",environment:"Chacras y áreas abiertas",note:"Seis individuos fueron identificados en el procedimiento de fauna silvestre de 2018.",source:"Argentina.gob.ar · Gendarmería Nacional",url:"https://www.argentina.gob.ar/noticias/rescatan-en-neuquen-53-aves-silvestres"},
{id:"F-009",type:"fauna",group:"ave",name:"Cisne de cuello negro",latin:"Cygnus melancoryphus",status:"documentado",statusLabel:"Registro georreferenciado",environment:"Ambientes acuáticos",note:"La Comisión Asesora de Fauna Silvestre registró 15 individuos en San Patricio del Chañar el 21/03/2023.",source:"Argentina.gob.ar · Comisión Asesora de Fauna Silvestre",url:"https://www.argentina.gob.ar/sites/default/files/2022/08/minuta_reunion_2_comision_asesora_de_fauna_silvestre_2023.pdf",lat:-38.59764,lng:-68.390522},
{id:"F-010",type:"fauna",group:"pez",name:"Pejerrey",latin:"Odontesthes sp.",status:"documentado",statusLabel:"Mencionado localmente",environment:"Río Neuquén",note:"La página turística municipal menciona pejerreyes entre los peces del río Neuquén utilizados para pesca deportiva en el entorno local.",source:"Municipalidad de San Patricio del Chañar",url:"https://sanpatricio.gob.ar/quehacer"},
{id:"F-011",type:"fauna",group:"pez",name:"Perca",latin:"Percichthys sp.",status:"documentado",statusLabel:"Mencionada localmente",environment:"Río Neuquén",note:"La Municipalidad menciona percas entre los peces presentes en el río Neuquén en el contexto de pesca deportiva.",source:"Municipalidad de San Patricio del Chañar",url:"https://sanpatricio.gob.ar/quehacer"},
{id:"F-012",type:"fauna",group:"pez",name:"Trucha",latin:"Oncorhynchus / Salmo sp.",status:"documentado",statusLabel:"Mencionada localmente",environment:"Río Neuquén",note:"La Municipalidad menciona truchas entre los peces del río Neuquén en el contexto de pesca deportiva. La identificación taxonómica precisa queda pendiente.",source:"Municipalidad de San Patricio del Chañar",url:"https://sanpatricio.gob.ar/quehacer"},
{id:"F-013",type:"fauna",group:"ave",name:"Más aves por descubrir",latin:"Registros pendientes de incorporación",status:"pendiente",statusLabel:"Investigación pendiente",environment:"Todo el territorio",note:"El Municipio informa que existen más de 25 especies de aves registradas en la zona. Este archivo irá incorporando nombres individuales a medida que encontremos fuentes locales verificables.",source:"Municipalidad de San Patricio del Chañar",url:"https://sanpatricio.gob.ar/quehacer"},
{id:"FL-001",type:"flora",group:"flora",name:"Flora del Dique Compensador",latin:"Inventario específico pendiente",status:"pendiente",statusLabel:"Investigación pendiente",environment:"Dique Compensador",note:"El Municipio reconoce el Dique Compensador como Área Natural Protegida Municipal desde 2006 y señala el valor de su flora y fauna autóctonas. Falta construir el inventario botánico específico con fuentes locales.",source:"Municipalidad de San Patricio del Chañar",url:"https://sanpatricio.gob.ar/nuestra"},
{id:"FL-002",type:"flora",group:"flora",name:"Flora ribereña",latin:"Inventario específico pendiente",status:"pendiente",statusLabel:"Investigación pendiente",environment:"Río Neuquén",note:"La actividad de kayak municipal se presenta como una forma de descubrir la flora y fauna del río. El proyecto debe documentar las especies concretas antes de publicarlas como registros locales.",source:"Municipalidad de San Patricio del Chañar",url:"https://sanpatricio.gob.ar/quehacer"},
{id:"FL-003",type:"flora",group:"flora",name:"Vegetación de chacras y canales",latin:"Inventario específico pendiente",status:"pendiente",statusLabel:"Investigación pendiente",environment:"Chacras y canales",note:"El paisaje productivo local combina cultivos, canales de riego y vegetación espontánea. La composición florística local será una línea de relevamiento propia del archivo.",source:"CONICET · investigación sobre comunidades de malezas en cultivos hortícolas de Neuquén",url:"https://www.researchgate.net/publication/255638210_Comunidades_de_malezas_en_cultivos_horticolas_en_la_Provincia_de_Neuquen_Argentina"}];

const grid=document.querySelector("#speciesGrid"), search=document.querySelector("#search"), count=document.querySelector("#countVisible"), dialog=document.querySelector("#speciesDialog"), dialogContent=document.querySelector("#dialogContent");
let activeFilter="all";

function card(r,i){return `<article class="species-card" data-id="${r.id}"><span class="index">${String(i+1).padStart(2,"0")}</span><span class="status-pill">${r.statusLabel}</span><div><span class="type">${r.type} · ${r.group==="ave"?"aves":r.group==="pez"?"peces":"flora"}</span><h3>${r.name}</h3><em>${r.latin}</em><p>${r.environment}</p><button onclick="openRecord('${r.id}')">Abrir ficha →</button></div></article>`}

function render(){const q=search.value.trim().toLowerCase();const visible=records.filter(r=>{const f=activeFilter==="all"||r.type===activeFilter||r.group===activeFilter||activeFilter==="pendiente"&&r.status==="pendiente";const text=[r.name,r.latin,r.environment,r.note,r.statusLabel].join(" ").toLowerCase();return f&&text.includes(q)});count.textContent=visible.length;grid.innerHTML=visible.length?visible.map(card).join(""):`<div class="empty">No encontramos ese registro todavía.<br>Eso también es parte del archivo: <b>investigación pendiente</b>.</div>`}

window.openRecord=function(id){const r=records.find(x=>x.id===id);if(!r)return;dialogContent.innerHTML=`<div class="dialog-body"><div class="eyebrow">${r.id} · ${r.statusLabel}</div><h2>${r.name}</h2><div class="latin">${r.latin}</div><p><strong>Ambiente:</strong> ${r.environment}</p><p>${r.note}</p><div class="source-box"><strong>Fuente</strong><br><a href="${r.url}" target="_blank" rel="noopener">${r.source} ↗</a></div></div>`;dialog.showModal();document.body.classList.add("no-scroll")};

document.querySelector("#closeDialog").onclick=()=>{dialog.close();document.body.classList.remove("no-scroll")};
dialog.addEventListener("click",e=>{if(e.target===dialog){dialog.close();document.body.classList.remove("no-scroll")}});
search.addEventListener("input",render);
document.querySelectorAll(".filter").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));btn.classList.add("active");activeFilter=btn.dataset.filter;render()}));

document.querySelector("#randomBtn").onclick=()=>{const r=records[Math.floor(Math.random()*records.length)];openRecord(r.id)};

document.querySelector("#menuBtn").onclick=()=>document.querySelector(".site-header nav").classList.toggle("mobile-open");
window.addEventListener("scroll",()=>document.querySelector(".site-header").classList.toggle("scrolled",scrollY>50));

const map=L.map("map",{scrollWheelZoom:false}).setView([-38.620,-68.390],11);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(map);
const localRecords=records.filter(r=>r.lat&&r.lng);
localRecords.forEach(r=>L.circleMarker([r.lat,r.lng],{radius:9,weight:2,fillOpacity:.8}).addTo(map).bindPopup(`<strong>${r.name}</strong><br>${r.latin}<br><small>${r.statusLabel}</small>`));
L.marker([-38.619,-68.390]).addTo(map).bindPopup("<strong>San Patricio del Chañar</strong><br>Centro aproximado del archivo natural.");

render();