const records=[
{id:"F-001",type:"fauna",group:"ave",name:"Calandria grande",latin:"Mimus saturninus",status:"documentado",statusLabel:"Registro local",environment:"Chacras y ambientes urbanos",note:"Mencionada expresamente por el Municipio entre las especies registradas en la zona.",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Mimus_saturninus_(6223460929).jpg",imageCredit:"Referencia visual · Wikimedia Commons",sourceRef:"municipalidad-quehacer"},
{id:"F-002",type:"fauna",group:"ave",name:"Carpintero real",latin:"Colaptes melanochloros",status:"documentado",statusLabel:"Registro local",environment:"Arbolado y chacras",note:"Incluido por el Municipio entre las especies destacadas del avistaje local.",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Colaptes_melanochloros_melanolaimus,_CABA.jpg",imageCredit:"Referencia visual · Wikimedia Commons",sourceRef:"municipalidad-quehacer"},
{id:"F-003",type:"fauna",group:"ave",name:"Golondrina patagónica",latin:"Tachycineta leucopyga",status:"documentado",statusLabel:"Registro local",environment:"Cielos abiertos y ambientes ribereños",note:"Mencionada por el Municipio entre las especies registradas en la zona.",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Tachycineta_leucopyga_1894.jpg",imageCredit:"Referencia visual · Wikimedia Commons",sourceRef:"municipalidad-quehacer"},
{id:"F-004",type:"fauna",group:"ave",name:"Cardenal copete rojo",latin:"Paroaria coronata",status:"documentado",statusLabel:"Registro local",environment:"Chacras",note:"19 individuos fueron identificados durante un procedimiento de fauna silvestre en una chacra local en 2018. El contexto fue de cautiverio.",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Paroaria_coronata_(Red-crested_Cardinal)_(48719959302).jpg",imageCredit:"Referencia visual · Wikimedia Commons",sourceRef:"rescate-aves-2018",count:"19 individuos",date:"2018"},
{id:"F-005",type:"fauna",group:"ave",name:"Jilguero",latin:"Carduelis carduelis",status:"documentado",statusLabel:"Registro local",environment:"Chacras",note:"22 individuos fueron identificados en el mismo procedimiento de 2018. Registro asociado a aves en cautiverio.",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Carduelis_carduelis.png",imageCredit:"Referencia visual · Wikimedia Commons",sourceRef:"rescate-aves-2018",count:"22 individuos",date:"2018"},
{id:"F-006",type:"fauna",group:"ave",name:"Zorzal",latin:"Turdus philomelos",status:"documentado",statusLabel:"Registro local",environment:"Chacras",note:"Cinco individuos fueron identificados en el procedimiento de fauna de 2018. El contexto fue de cautiverio.",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Turdus_philomelos.jpg",imageCredit:"Referencia visual · Wikimedia Commons",sourceRef:"rescate-aves-2018",count:"5 individuos",date:"2018"},
{id:"F-007",type:"fauna",group:"ave",name:"Pica hueso",latin:"Saltator aurantiirostris",status:"documentado",statusLabel:"Registro local",environment:"Chacras",note:"Un individuo fue identificado en el procedimiento de fauna silvestre de 2018.",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Saltator_aurantiirostris_-_Golden-billed_Saltator;_Capivara,_Santa_Fe,_Argentina.jpg",imageCredit:"Referencia visual · Wikimedia Commons",sourceRef:"rescate-aves-2018",count:"1 individuo",date:"2018"},
{id:"F-008",type:"fauna",group:"ave",name:"Loica",latin:"Sturnella loyca",status:"documentado",statusLabel:"Registro local",environment:"Chacras y áreas abiertas",note:"Seis individuos fueron identificados en el procedimiento de fauna silvestre de 2018.",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Loyca.jpg",imageCredit:"Referencia visual · Wikimedia Commons",sourceRef:"rescate-aves-2018",count:"6 individuos",date:"2018"},
{id:"F-009",type:"fauna",group:"ave",name:"Cisne de cuello negro",latin:"Cygnus melancoryphus",status:"documentado",statusLabel:"Registro georreferenciado",environment:"Ambientes acuáticos",note:"La Comisión Asesora de Fauna Silvestre registró 15 individuos en San Patricio del Chañar el 21/03/2023.",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Cisne_de_cuello_negro_-_A740080.jpg",imageCredit:"Referencia visual · Wikimedia Commons",sourceRef:"cisne-2023",lat:-38.59764,lng:-68.390522,date:"21/03/2023",count:"15 individuos"},
{id:"F-010",type:"fauna",group:"pez",name:"Pejerrey",latin:"Odontesthes sp.",status:"documentado",statusLabel:"Mencionado localmente",environment:"Río Neuquén",note:"La página turística municipal menciona pejerreyes entre los peces del río Neuquén en contexto de pesca deportiva.",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/FotografíaPejerreyVacas.jpg",imageCredit:"Referencia visual · Wikimedia Commons",sourceRef:"municipalidad-quehacer"},
{id:"F-011",type:"fauna",group:"pez",name:"Perca",latin:"Percichthys sp.",status:"documentado",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Perca_trucha_(Percichthys_trucha).JPG",imageCredit:"Referencia visual · Wikimedia Commons",statusLabel:"Mencionada localmente",environment:"Río Neuquén",note:"La Municipalidad menciona percas entre los peces presentes en el río Neuquén.",sourceRef:"municipalidad-quehacer"},
{id:"F-012",type:"fauna",group:"pez",name:"Trucha",latin:"Oncorhynchus / Salmo sp.",status:"documentado",statusLabel:"Mencionada localmente",environment:"Río Neuquén",note:"La Municipalidad menciona truchas. La identificación taxonómica precisa queda pendiente.",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Oncorhynchus_mykiss.jpg",imageCredit:"Referencia visual · Wikimedia Commons",sourceRef:"municipalidad-quehacer"},
{id:"FL-001",type:"flora",group:"flora",name:"Flora del Dique Compensador",latin:"Inventario específico pendiente",status:"pendiente",statusLabel:"Investigación pendiente",environment:"Dique Compensador",note:"El Municipio reconoce el Dique Compensador como Área Natural Protegida Municipal desde 2006 y señala el valor de su flora y fauna autóctonas. Falta construir el inventario botánico específico.",sourceRef:"municipalidad-nuestra"},
{id:"FL-002",type:"flora",group:"flora",name:"Flora ribereña",latin:"Inventario específico pendiente",status:"pendiente",statusLabel:"Investigación pendiente",environment:"Río Neuquén",note:"La actividad de kayak municipal se presenta como una forma de descubrir flora y fauna del río. Las especies concretas quedan pendientes.",sourceRef:"municipalidad-quehacer"},
{id:"FL-003",type:"flora",group:"flora",name:"Vegetación de chacras y canales",latin:"Inventario específico pendiente",status:"pendiente",statusLabel:"Investigación pendiente",environment:"Chacras y canales",note:"El paisaje productivo combina cultivos, canales y vegetación espontánea. La composición florística local será una línea de relevamiento propia.",sourceRef:"flora-neuquen"}
];

const extraKnowledge={
"F-001":{recognition:"Ave de tamaño mediano, cola larga y gran capacidad para imitar sonidos.",diet:"Omnívora; consume una combinación de frutos, semillas y pequeños animales.",behavior:"Suele verse sola o en pareja y utiliza ambientes abiertos y arbolados.",local:"El Municipio la incluye entre las aves registradas en San Patricio del Chañar.",question:"¿En qué sectores de Chañar se la observa con mayor frecuencia?"},
"F-002":{recognition:"Carpintero de pico fuerte, adaptado a buscar alimento sobre madera.",diet:"Principalmente insectos y otros pequeños invertebrados asociados a la madera.",behavior:"Explora troncos y ramas y puede excavar cavidades.",local:"El Municipio lo incluye entre las aves registradas localmente.",question:"¿Qué árboles y ambientes utiliza en Chañar?"},
"F-003":{recognition:"Golondrina de vuelo rápido, especializada en capturar alimento mientras vuela.",diet:"Principalmente insectos aéreos.",behavior:"Pasa buena parte del tiempo en vuelo y utiliza espacios abiertos.",local:"El Municipio la menciona entre las aves registradas en Chañar.",question:"¿Cuándo aparece y en qué lugares del valle se concentra?"},
"F-004":{recognition:"Ave de plumaje rojo intenso en la cabeza y cresta característica.",diet:"Semillas, frutos e invertebrados; la proporción cambia según la disponibilidad.",behavior:"Frecuenta ambientes abiertos con vegetación y puede acercarse a áreas humanizadas.",local:"En 2018 se documentaron 19 individuos en una chacra local, dentro de un procedimiento de aves en cautiverio. No es un registro de población silvestre.",question:"¿Existe evidencia local de ejemplares silvestres?"},
"F-005":{recognition:"Pequeño fringílido de pico corto, asociado a semillas.",diet:"Principalmente semillas; también puede aprovechar otros recursos vegetales.",behavior:"Puede moverse en grupos y explorar vegetación baja.",local:"La fuente de 2018 documenta 22 individuos en cautiverio en una chacra local.",question:"¿Hay registros silvestres locales verificables?"},
"F-006":{recognition:"Zorzal identificado en la documentación de 2018; la identificación local requiere revisión.",diet:"La información de dieta de este registro queda pendiente de corroboración.",behavior:"El registro disponible es documental y de cautiverio, no una observación ecológica local.",local:"La fuente de 2018 registra 5 individuos en una chacra local en contexto de cautiverio.",question:"¿La identificación taxonómica del registro coincide con la especie observada?"},
"F-007":{recognition:"Ave robusta de pico fuerte, asociada a ambientes arbustivos y abiertos.",diet:"Semillas, frutos e invertebrados; en estudios regionales se documentan hormigas aladas y frutos/semillas.",behavior:"Puede encontrarse sola o en pareja entre arbustos y sobre el suelo.",local:"La documentación de 2018 registra 1 individuo en cautiverio en una chacra local.",question:"¿Dónde se lo observa libremente en Chañar?"},
"F-008":{recognition:"Ave de campo de tonos oscuros y vientre rojizo, asociada a espacios abiertos.",diet:"Principalmente semillas e invertebrados según disponibilidad.",behavior:"Utiliza áreas abiertas y puede desplazarse sobre el suelo.",local:"La fuente de 2018 registra 6 individuos en cautiverio en una chacra local.",question:"¿Qué ambientes abiertos del Chañar utiliza?"},
"F-009":{recognition:"Gran ave acuática de cuello negro y cuerpo claro; muy reconocible sobre el agua.",diet:"Busca alimento en ambientes acuáticos, incluyendo vegetación y otros recursos disponibles.",behavior:"Nada, descansa, se acicala y se alimenta en cuerpos de agua.",local:"Hay un registro oficial de 15 individuos en San Patricio del Chañar el 21/03/2023, con coordenadas publicadas.",question:"¿Es un visitante estacional o permanece en la zona durante distintos períodos?"},
"F-010":{recognition:"Pez de cuerpo alargado asociado a ambientes de agua dulce.",diet:"La dieta exacta de los ejemplares locales requiere documentación específica.",behavior:"Relacionado con ambientes acuáticos del Río Neuquén.",local:"El Municipio menciona pejerrey en el Río Neuquén dentro del contexto de pesca deportiva.",question:"¿Qué especie de pejerrey está presente realmente en este tramo del río?"},
"F-011":{recognition:"Pez de agua dulce de cuerpo robusto, conocido localmente como perca.",diet:"La dieta de la población local requiere documentación específica.",behavior:"Habita ambientes acuáticos y forma parte de la fauna íctica del río.",local:"El Municipio menciona perca en el Río Neuquén.",question:"¿Qué características tiene la población local y cómo cambia durante el año?"},
"F-012":{recognition:"Pez de agua dulce introducido en distintos sistemas de Patagonia; la especie exacta del registro local requiere precisión.",diet:"La dieta depende de la especie y del ambiente; queda pendiente para Chañar.",behavior:"Asociada a aguas con condiciones adecuadas para salmónidos.",local:"El Municipio menciona trucha en el Río Neuquén.",question:"¿Qué especie de trucha está presente y en qué sectores del río?"},
"FL-001":{recognition:"Línea de investigación sobre la vegetación nativa y natural del Dique Compensador.",diet:"No corresponde.",behavior:"Las plantas sostienen alimento, refugio y estructura del ambiente.",local:"El Dique Compensador es Área Natural Protegida Municipal desde 2006; el inventario botánico específico sigue pendiente.",question:"¿Qué especies de plantas nativas crecen allí?"},
"FL-002":{recognition:"Vegetación que crece en las orillas y acompaña cursos y cuerpos de agua.",diet:"No corresponde.",behavior:"Puede estabilizar orillas, ofrecer refugio y sostener cadenas alimentarias.",local:"La existencia de flora ribereña es una línea de relevamiento local; falta un inventario específico de Chañar.",question:"¿Qué especies forman la vegetación ribereña local?"},
"FL-003":{recognition:"Vegetación vinculada al paisaje agrícola, canales y bordes de chacras.",diet:"No corresponde.",behavior:"Las plantas de los bordes agrícolas pueden ofrecer alimento y refugio a fauna.",local:"Existe bibliografía sobre comunidades de malezas en cultivos hortícolas de Neuquén, pero no debe convertirse automáticamente en inventario de Chañar.",question:"¿Qué plantas aparecen realmente en chacras y canales de Chañar?"}
};

const SOURCES={
"municipalidad-quehacer":{label:"Municipalidad de San Patricio del Chañar · Qué hacer",url:"https://sanpatricio.gob.ar/quehacer"},
"municipalidad-nuestra":{label:"Municipalidad de San Patricio del Chañar · Área Natural Protegida",url:"https://sanpatricio.gob.ar/nuestra"},
"gendarmeria-aves-2018":{label:"Argentina.gob.ar · rescate de aves silvestres en Neuquén",url:"https://www.argentina.gob.ar/noticias/rescatan-en-neuquen-53-aves-silvestres"},
"fauna-comision-2023":{label:"Argentina.gob.ar · Comisión Asesora de Fauna Silvestre",url:"https://www.argentina.gob.ar/sites/default/files/2022/08/minuta_reunion_2_comision_asesora_de_fauna_silvestre_2023.pdf"},
"ambiente-neuquen-2022":{label:"Ambiente Neuquén · siembra educativa de alevinos",url:"https://ambiente.neuquen.gov.ar/siembra-educativa-de-alevinos-en-san-patricio-del-chanar-2/"},
"researchgate-neuquen":{label:"Investigación sobre comunidades de malezas en Neuquén",url:"https://www.researchgate.net/publication/255638210_Comunidades_de_malezas_en_cultivos_horticolas_en_la_Provincia_de_Neuquen_Argentina"}
};
const ENV_KEYS={rio:["río","ribereño","agua","acuático"],chacras:["chacra","cultivo","canales","urbano","arbolado"],dique:["dique","humedal"],monte:["monte","natural","vegetación"]};
const $=s=>document.querySelector(s);
const $$=s=>Array.from(document.querySelectorAll(s));
const state={filter:"all",lastFocus:null};
function escapeHTML(value){return String(value??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function getRecord(id){return records.find(r=>r.id===id)||null;}
function sourceFor(record){return SOURCES[record?.sourceRef]||null;}
function imageMarkup(record){if(!record?.image)return '<div class="dialog-image species-photo-empty" role="img" aria-label="Fotografía local pendiente"></div>';return '<div class="dialog-image"><img src="'+escapeHTML(record.image)+'" alt="Referencia visual de '+escapeHTML(record.name)+'" decoding="async"><span class="tag">REFERENCIA VISUAL · '+escapeHTML(record.imageCredit||"Fuente visual externa")+'</span></div>';}
function cardMarkup(record){const k=extraKnowledge[record.id]||{};const type=record.type==="flora"?"FLORA":record.group==="ave"?"AVE":"FAUNA";return '<button class="species-card" type="button" data-open="'+escapeHTML(record.id)+'">'+(record.image?'<div class="species-photo"><img src="'+escapeHTML(record.image)+'" alt="" loading="lazy" decoding="async"><span>REFERENCIA VISUAL</span></div>':'<div class="species-photo species-photo-empty"><span>IMAGEN LOCAL PENDIENTE</span></div>')+'<div class="species-card-body"><span class="status">'+escapeHTML(record.statusLabel)+'</span><span class="type">'+type+'</span><h3>'+escapeHTML(record.name)+'</h3><em>'+escapeHTML(record.latin)+'</em><p class="teaser">'+escapeHTML(k.local||record.note)+'</p></div></button>';}
function renderGrid(){const visible=records.filter(r=>state.filter==="all"||r.type===state.filter);$("#speciesGrid").innerHTML=visible.map(cardMarkup).join("");$("#speciesStatus").textContent=visible.length+" fichas disponibles · tocá una para entrar";$$("[data-open]").forEach(button=>button.addEventListener("click",()=>openRecord(button.dataset.open)));}
function panelMarkup(id,title,body,active=false){return '<section class="fact-panel'+(active?" active":"")+'" data-panel="'+id+'"'+(active?'':' hidden')+'><h3>'+title+'</h3>'+body+'</section>';}
function fact(label,value){return '<div class="fact"><b>'+label+'</b><span>'+escapeHTML(value||"Investigación pendiente.")+'</span></div>';}
function openRecord(id){const record=getRecord(id);if(!record)return;state.lastFocus=document.activeElement;const k=extraKnowledge[id]||{};const source=sourceFor(record);const sourceHtml=source?'<a href="'+escapeHTML(source.url)+'" target="_blank" rel="noopener noreferrer">'+escapeHTML(source.label)+'</a>':"Procedencia detallada pendiente.";$("#dialogContent").innerHTML='<div class="dialog-wrap">'+imageMarkup(record)+'<div class="dialog-copy"><span class="eyebrow">'+escapeHTML(record.statusLabel)+' · '+escapeHTML(record.id)+'</span><h2 id="dialogTitle">'+escapeHTML(record.name)+'</h2><div class="latin">'+escapeHTML(record.latin)+'</div><p class="intro-note">'+escapeHTML(record.note)+'</p><div class="fact-nav" role="tablist" aria-label="Información de la especie"><button class="active" type="button" role="tab" aria-selected="true" data-tab="mira">MIRÁ</button><button type="button" role="tab" aria-selected="false" data-tab="vive">CÓMO VIVE</button><button type="button" role="tab" aria-selected="false" data-tab="chañar">EN CHAÑAR</button><button type="button" role="tab" aria-selected="false" data-tab="archivo">ARCHIVO</button></div>'+panelMarkup("mira","¿Qué estás viendo?",'<p>'+escapeHTML(k.recognition||"La descripción visual detallada está pendiente de documentación específica.")+'</p><div class="fact-grid">'+fact("NOMBRE CIENTÍFICO",record.latin)+fact("AMBIENTE ASOCIADO",record.environment)+fact("TIPO",record.type==="flora"?"Flora":record.group==="ave"?"Ave":"Fauna")+fact("EVIDENCIA",record.statusLabel)+'</div>',true)+panelMarkup("vive","Su vida",'<div class="fact-grid">'+fact("ALIMENTACIÓN",k.diet)+fact("COMPORTAMIENTO",k.behavior)+fact("AMBIENTE",record.environment)+fact("QUÉ BUSCAR",k.recognition)+'</div>')+panelMarkup("chañar","La pregunta local",'<p>'+escapeHTML(k.local||record.note)+'</p>'+fact("LO QUE TODAVÍA QUEREMOS SABER",k.question||"Faltan registros locales para completar esta ficha.")+fact("AMBIENTE",record.environment))+panelMarkup("archivo","¿De dónde sale?",'<p>'+escapeHTML(record.note)+'</p><div class="source-note"><b>FUENTE PRINCIPAL</b><br>'+sourceHtml+'<br><br>Una fotografía de referencia sirve para reconocer la especie; no significa que esa imagen haya sido tomada en San Patricio del Chañar.</div>')+'</div></div>';dialog.showModal();document.body.classList.add("no-scroll");bindTabs();bindDialogImageErrors();$("#closeDialog").focus();}
function bindTabs(){const tabs=$$(".fact-nav [data-tab]"),panels=$$("[data-panel]");tabs.forEach(tab=>tab.addEventListener("click",()=>{tabs.forEach(t=>{const active=t===tab;t.classList.toggle("active",active);t.setAttribute("aria-selected",String(active));});panels.forEach(panel=>{const active=panel.dataset.panel===tab.dataset.tab;panel.classList.toggle("active",active);panel.hidden=!active;});}));}
function bindDialogImageErrors(){const img=$("#dialogContent img");if(img)img.addEventListener("error",()=>{img.closest(".dialog-image").classList.add("species-photo-empty");img.remove();});}
function closeDialog(){if(!dialog.open)return;dialog.close();document.body.classList.remove("no-scroll");if(state.lastFocus?.focus)state.lastFocus.focus();}
function openObservation(){state.lastFocus=document.activeElement;$("#dialogContent").innerHTML='<div class="dialog-copy"><span class="eyebrow">CHAÑAR VIVO · NUEVO REGISTRO</span><h2 id="dialogTitle">¿Qué viste?</h2><p class="intro-note">Dejá una pista. No inventamos una especie: guardamos una observación local como borrador en este dispositivo.</p><form class="observation-form" id="obs"><label>QUÉ VISTE</label><div class="obs-buttons"><button type="button" data-v="Animal">Animal</button><button type="button" data-v="Planta">Planta</button><button type="button" data-v="Huella">Huella</button><button type="button" data-v="Sonido">Sonido</button><button type="button" data-v="No sé">No sé qué es</button></div><input type="hidden" id="obsType"><label for="obsPlace">DÓNDE</label><input id="obsPlace" autocomplete="off" placeholder="Río, chacra, canal, barrio..."><label for="obsDate">CUÁNDO</label><input id="obsDate" type="date"><label for="obsNote">CONTANOS</label><textarea id="obsNote" rows="5" placeholder="Color, tamaño, cantidad, comportamiento..."></textarea><p class="observation-help">No se publica automáticamente ni se envía a ningún servidor.</p><button class="hero-button" type="submit">GUARDAR BORRADOR →</button></form></div>';dialog.showModal();document.body.classList.add("no-scroll");$$("[data-v]").forEach(button=>button.addEventListener("click",()=>{$$("[data-v]").forEach(x=>x.classList.remove("active"));button.classList.add("active");$("#obsType").value=button.dataset.v;}));$("#obs").addEventListener("submit",saveObservation);$("#obsType").focus();}
function saveObservation(event){event.preventDefault();const payload={type:$("#obsType").value||"No indicado",place:$("#obsPlace").value.trim()||"No indicado",date:$("#obsDate").value||"No indicada",note:$("#obsNote").value.trim()||"Sin descripción"};try{localStorage.setItem("ocarinaWildLastObservation",JSON.stringify(payload));$("#dialogContent").innerHTML='<div class="dialog-copy"><span class="eyebrow">LISTO</span><h2 id="dialogTitle">La observación quedó preparada.</h2><p class="intro-note">Se guardó como borrador en este dispositivo. Todavía no se publica.</p><button class="hero-button" type="button" id="doneObservation">VOLVER →</button></div>';$("#doneObservation").addEventListener("click",closeDialog);}catch(error){$("#dialogContent").innerHTML='<div class="dialog-copy"><span class="eyebrow">NO SE PUDO GUARDAR</span><h2 id="dialogTitle">La observación sigue acá.</h2><p class="intro-note">El navegador no permitió guardar el borrador. Copiá tus datos antes de cerrar.</p></div>';console.error("OCARINA WILD storage error",error);}}
function filterBy(kind){state.filter=kind;$$(".switch button").forEach(button=>{const active=button.dataset.kind===kind;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active));});renderGrid();}
function surprise(){if(!records.length)return;const record=records[Math.floor(Math.random()*records.length)];openRecord(record.id);}
function exploreEnvironment(key){const tokens=ENV_KEYS[key]||[];const matches=records.filter(record=>tokens.some(token=>(record.environment||"").toLowerCase().includes(token)));openRecord((matches[0]||records[0])?.id);}
const dialog=$("#speciesDialog");
$$(".switch button").forEach(button=>button.addEventListener("click",()=>filterBy(button.dataset.kind)));
$("#surprise").addEventListener("click",surprise);
$$("[data-env]").forEach(button=>button.addEventListener("click",()=>exploreEnvironment(button.dataset.env)));
$("#observe").addEventListener("click",openObservation);
$("#closeDialog").addEventListener("click",closeDialog);
dialog.addEventListener("click",event=>{if(event.target===dialog)closeDialog();});
dialog.addEventListener("cancel",event=>{event.preventDefault();closeDialog();});
document.addEventListener("keydown",event=>{if(event.key==="Escape"&&dialog.open)closeDialog();});
renderGrid();