/* OCARINA WILD · BASE DE INVESTIGACIÓN LOCAL v2.0
   Criterio: no confundir presencia local, referencia regional y candidato de investigación.
*/
export const SOURCES = {
  muni: {label:"Municipalidad de San Patricio del Chañar", url:"https://sanpatricio.gob.ar/quehacer"},
  muniNatural: {label:"Municipalidad · Dique Compensador y territorio", url:"https://sanpatricio.gob.ar/nuestra"},
  sib: {label:"Sistema de Información de Biodiversidad · Parques Nacionales", url:"https://sib.gob.ar/"},
  sibChañar: {label:"SIB · Geoffroea decorticans", url:"https://sib.gob.ar/especies/geoffroea-decorticans"},
  sibJarilla: {label:"SIB · Larrea divaricata", url:"https://sib.gob.ar/especies/larrea-divaricata"},
  sibAtajacaminos: {label:"SIB · Systellura longirostris", url:"https://sib.gob.ar/especies/systellura-longirostris"},
  unco: {label:"UNCo / investigación territorial de Añelo y Dique Compensador El Chañar", url:"https://www.researchgate.net/publication/341833531_Proyecto_de_Desarrollo_Tecnologico_y_Social_PDTS_CIN-CONICET_Impactos_y_conflictos_de_la_explotacion_hidrocarburifera_en_Vaca_Muerta_Hacia_una_estrategia_para_el_desarrollo_de_la_localidad_de_Anelo_Ne"},
  monte: {label:"EIA Neuquén · Provincia fitogeográfica del Monte", url:"https://ambiente.neuquen.gov.ar/wp-content/uploads/2023/03/EIA-Integral-PPar.pdf"},
  pesca: {label:"Reglamento de Pesca Deportiva Continental Patagónico", url:"https://reglamentodepesca.org.ar/reglamento-items/ambientes-neuquen/"}
};

export const SPECIES = [
 {id:"calandria-grande",type:"fauna",group:"aves",name:"Calandria grande",scientific:"Mimus saturninus",zone:"Chacras",status:"local",certainty:"mención municipal local",summary:"Ave registrada entre las especies destacadas por el Municipio para el avistaje en la zona.",habitat:"Áreas abiertas, arboladas y humanizadas.",season:"Por relevar localmente.",source:["muni"]},
 {id:"carpintero-real",type:"fauna",group:"aves",name:"Carpintero real",scientific:"Colaptes melanochloros",zone:"Chacras / arbolado",status:"local",certainty:"mención municipal local",summary:"Especie destacada por el Municipio dentro de las aves registradas en la zona.",habitat:"Sectores arbolados.",season:"Por relevar localmente.",source:["muni"]},
 {id:"golondrina-patagonica",type:"fauna",group:"aves",name:"Golondrina patagónica",scientific:"Tachycineta leucopyga",zone:"Río / espacios abiertos",status:"local",certainty:"mención municipal local",summary:"Especie destacada por el Municipio dentro de las aves registradas en la zona.",habitat:"Espacios abiertos y cercanías del agua.",season:"Por relevar localmente.",source:["muni"]},
 {id:"atajacamino-nanarca",type:"fauna",group:"aves",name:"Atajacaminos ñañarca",scientific:"Systellura longirostris",zone:"Dique / monte",status:"documentada",certainty:"registro científico en Dique El Chañar",summary:"El SIB registra una cita de 2017 en un sector ubicado al final de la presa lateral del Dique El Chañar sobre el río Neuquén.",habitat:"Estepa arbustiva, claros y caminos; actividad crepuscular/nocturna.",season:"Residente de verano del noroeste patagónico según SIB.",source:["sibAtajacaminos"]},
 {id:"pejerrey",type:"fauna",group:"peces",name:"Pejerrey",scientific:"Odontesthes sp.",zone:"Río / Dique",status:"local",certainty:"mención municipal + reglamentación pesquera",summary:"El Municipio identifica pejerreyes entre los peces del río Neuquén utilizados para pesca deportiva. La especie exacta debe determinarse en campo.",habitat:"Ambientes acuáticos.",season:"Por relevar.",source:["muni","pesca"]},
 {id:"perca",type:"fauna",group:"peces",name:"Perca",scientific:"Percichthys sp.",zone:"Río / Dique",status:"local",certainty:"mención municipal + reglamentación pesquera",summary:"El Municipio menciona percas en el río Neuquén. La ficha mantiene el género hasta lograr identificación específica.",habitat:"Río y ambientes acuáticos asociados.",season:"Por relevar.",source:["muni","pesca"]},
 {id:"trucha-arcoiris",type:"fauna",group:"peces",name:"Trucha arco iris",scientific:"Oncorhynchus mykiss",zone:"Río",status:"local",certainty:"mención/reglamentación regional",summary:"La reglamentación pesquera incluye trucha arco iris para ambientes del sistema Neuquén. La ficha requiere confirmar el punto exacto de presencia en Chañar.",habitat:"Ambientes acuáticos.",season:"Según reglamentación vigente.",source:["pesca"]},
 {id:"mara",type:"fauna",group:"mamiferos",name:"Mara",scientific:"Dolichotis patagonum",zone:"Monte",status:"referencia regional",certainty:"fauna regional del Monte / mención secundaria local",summary:"Mamífero característico de ambientes abiertos patagónicos. La presencia puntual en Chañar requiere registro local.",habitat:"Estepas y ambientes abiertos.",season:"Por relevar.",source:["monte"]},
 {id:"zorro-gris",type:"fauna",group:"mamiferos",name:"Zorro gris",scientific:"Lycalopex gymnocercus",zone:"Monte / borde rural",status:"referencia regional",certainty:"mención secundaria local",summary:"Depredador generalista asociado a ambientes abiertos y rurales. Falta un registro local georreferenciado en el archivo Ocarina.",habitat:"Monte, bordes rurales y ambientes intervenidos.",season:"Por relevar.",source:["monte"]},
 {id:"cuis",type:"fauna",group:"mamiferos",name:"Cuis",scientific:"Microcavia australis",zone:"Monte",status:"referencia regional",certainty:"fauna regional",summary:"Pequeño roedor frecuente en ambientes áridos del Monte. La presencia local debe comprobarse mediante observación o registro fotográfico.",habitat:"Matorrales y sectores abiertos.",season:"Por relevar.",source:["monte"]},
 {id:"piche",type:"fauna",group:"mamiferos",name:"Piche",scientific:"Zaedyus pichiy",zone:"Monte",status:"candidato",certainty:"candidato de investigación local",summary:"Candidato para búsqueda de huellas, cuevas y avistajes en ambientes de monte. No se presenta como registro confirmado de Chañar.",habitat:"Ambientes áridos y abiertos.",season:"Por relevar.",source:["monte"]},
 {id:"lagarto-overo",type:"fauna",group:"reptiles",name:"Lagarto overo",scientific:"Salvator merianae",zone:"Monte / ribera",status:"candidato",certainty:"mención secundaria local",summary:"Reptil grande ampliamente distribuido en Argentina; se incorpora como línea de investigación, no como registro confirmado.",habitat:"Ambientes abiertos, bordes de vegetación y sectores próximos al agua.",season:"Mayor actividad en épocas cálidas.",source:["monte"]},
 {id:"yarara",type:"fauna",group:"reptiles",name:"Yarará",scientific:"Bothrops sp.",zone:"Monte",status:"candidato",certainty:"mención secundaria local; especie pendiente",summary:"La categoría local requiere identificación segura antes de asignar especie. No se recomienda buscarla ni manipularla.",habitat:"Ambientes naturales; detalle local pendiente.",season:"Por relevar sin intervención.",source:["muni"]},

 {id:"chanar",type:"flora",group:"arboles",name:"Chañar",scientific:"Geoffroea decorticans",zone:"Ribera / monte / chacras",status:"prioridad",certainty:"especie autóctona y emblemática",summary:"Árbol nativo de 4–8 m, caducifolio y espinoso. Forma bosquecillos o isletas y posee raíces gemíferas.",habitat:"Valles, cañadones y sectores con disponibilidad de agua.",season:"Floración primaveral; fructificación hacia fines de primavera/verano según SIB.",source:["sibChañar","muni"]},
 {id:"jarilla-hembra",type:"flora",group:"arbustos",name:"Jarilla hembra",scientific:"Larrea divaricata",zone:"Monte",status:"regional",certainty:"especie autóctona del Monte; presencia local a verificar",summary:"Arbusto característico de la provincia fitogeográfica del Monte. El EIA provincial identifica a las jarillas como componentes dominantes del Monte.",habitat:"Arbustales xerófilos.",season:"Por relevar.",source:["sibJarilla","monte"]},
 {id:"jarilla-macho",type:"flora",group:"arbustos",name:"Jarilla macho",scientific:"Larrea cuneifolia",zone:"Monte",status:"regional",certainty:"especie del Monte; presencia local a verificar",summary:"Arbusto xerófilo del Monte. SIB describe comunidades donde puede convivir con L. divaricata.",habitat:"Ambientes secos y arbustales.",season:"Por relevar.",source:["sib","monte"]},
 {id:"zampa",type:"flora",group:"arbustos",name:"Zampa",scientific:"Atriplex lampa",zone:"Monte / suelo salino",status:"regional",certainty:"autóctona; presencia local a verificar",summary:"Subarbusto autóctono asociado a ambientes áridos y del Monte.",habitat:"Suelos secos y ambientes con condiciones salinas.",season:"Por relevar.",source:["sib"]},
 {id:"piquillin",type:"flora",group:"arbustos",name:"Piquillín de las víboras",scientific:"Lycium chilense",zone:"Monte",status:"regional",certainty:"autóctona; presencia neuquina documentada, Chañar pendiente",summary:"Arbusto autóctono de porte bajo a medio. Se incorpora para buscar registros locales y diferenciarlo de especies similares.",habitat:"Ambientes áridos.",season:"Por relevar.",source:["sib"]},
 {id:"sauce",type:"flora",group:"ribera",name:"Sauce",scientific:"Salix sp.",zone:"Ribera",status:"local",certainty:"mención local secundaria",summary:"Los registros comunitarios consultados describen sauces en la costa del río. La especie y condición —nativa o introducida— deben separarse en el inventario.",habitat:"Bordes de cursos de agua.",season:"Por relevar.",source:["muni"]},
 {id:"alamo",type:"flora",group:"arboles",name:"Álamo",scientific:"Populus sp.",zone:"Chacras / ribera",status:"local",certainty:"vegetación implantada mencionada localmente",summary:"Árbol de uso productivo y ornamental en el valle. Ocarina lo tratará como flora implantada, no como nativa.",habitat:"Chacras, cortinas y espacios intervenidos.",season:"Por relevar.",source:["muni"]},
 {id:"eucalipto",type:"flora",group:"arboles",name:"Eucalipto",scientific:"Eucalyptus sp.",zone:"Chacras / arbolado",status:"local",certainty:"vegetación implantada mencionada localmente",summary:"Especie implantada presente en el paisaje humano. Se separa editorialmente de la flora nativa.",habitat:"Áreas productivas y urbanas.",season:"Por relevar.",source:["muni"]},

 {id:"rio-neuquen",type:"territorio",group:"ambiente",name:"Río Neuquén",zone:"Agua",status:"territorio",certainty:"ambiente central",summary:"Corredor de agua que estructura parte de la vida natural y productiva local.",habitat:"Ribera, agua abierta, islas, bordes vegetados.",season:"Dinámica anual.",source:["muni"]},
 {id:"dique-compensador",type:"territorio",group:"ambiente",name:"Dique Compensador El Chañar",zone:"Dique",status:"protegido",certainty:"Área Natural Protegida Municipal",summary:"Ambiente declarado Área Natural Protegida Municipal en 2006. La investigación territorial identifica al sitio como especialmente interesante para observación de aves por la diversidad de ambientes que concentra.",habitat:"Aguas profundas y bajas, juncales, vegetación de ribera, monte y área rural.",season:"Todo el año; riqueza estacional por relevar.",source:["muniNatural","unco"]},
 {id:"chacras-riego",type:"territorio",group:"ambiente",name:"Chacras y red de riego",zone:"Chacras",status:"territorio",certainty:"ambiente productivo",summary:"El valle productivo combina cultivos, arbolado, canales y espacios humanizados que también funcionan como hábitat.",habitat:"Chacras, canales, bordes vegetados e infraestructura rural.",season:"Ciclo anual.",source:["muniNatural"]},
 {id:"monte-chañar",type:"territorio",group:"ambiente",name:"Monte",zone:"Monte",status:"ecorregion",certainty:"marco fitogeográfico",summary:"El Monte se caracteriza por arbustales xerófilos, con jarillas como componentes principales y comunidades asociadas a suelos salinos o arenosos.",habitat:"Arbustales secos y suelos con distinta disponibilidad de agua.",season:"Fuerte estacionalidad.",source:["monte"]}
];

export const ZONES = ["Todos","Río","Dique","Chacras","Monte","Agua","Ribera","Cielo"];
export const DOORS = {
 fauna:{label:"FAUNA",subtitle:"aves · peces · mamíferos · reptiles",intro:"Quiénes viven, pasan, cazan, nadan, vuelan o dejan huellas en el territorio.",groups:["aves","peces","mamiferos","reptiles"]},
 flora:{label:"FLORA",subtitle:"árboles · arbustos · ribera · monte",intro:"La vegetación como identidad, refugio, alimento y lectura del paisaje.",groups:["arboles","arbustos","ribera"]},
 territorio:{label:"TERRITORIO",subtitle:"río · dique · chacras · monte",intro:"Los ambientes primero. Las especies después: cada vida necesita un lugar que explique su presencia.",groups:["ambiente"]},
 archivo:{label:"ARCHIVO",subtitle:"fuentes · evidencia · observaciones · método",intro:"La capa que impide que Ocarina convierta una suposición en un hecho.",groups:[]}
};
