import { records } from "./data/catalog.js";
import { inventoryRecords, regionalReferencePool } from "./data/inventory-3-17.js";
import { wild320Sources, wild320Principles, wild320Territories, wild320Evidence, WILD_320_VERSION, WILD_320_LAW } from "./data/wild-3-20.js";
const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function init(){if(document.querySelector("#wild320"))return;const l=document.createElement("link");l.rel="stylesheet";l.href="./wild-3-20.css";l.dataset.wild320="";document.head.append(l);
const root=document.createElement("section");root.id="wild320";root.className="wild320";
root.innerHTML='<div class="w320-hero"><div class="w320-hero-copy"><span class="w320-eyebrow">OCARINA WILD · '+WILD_320_VERSION+'</span><h2>UN TERRITORIO<br><i>QUE SE DEJA DESCUBRIR.</i></h2><p>Fauna, flora, agua, chacras, monte, fuentes y memoria reunidos en una sola experiencia.</p><div class="w320-actions"><button data-jump="explorar">EXPLORAR</button><button class="ghost" data-jump="territorio">VER TERRITORIO</button></div></div><div class="w320-hero-art" aria-label="Ilustración del territorio vivo" role="img"><div class="w320-sun"></div><div class="w320-ridge"></div><div class="w320-water"></div><div class="w320-bird b1">⌁</div><div class="w320-bird b2">⌁</div><span>CHAÑAR · AGUA · VIENTO · VIDA</span></div></div>'+
'<div class="w320-intro"><span>LEY MUNDIAL · 3.20</span><h3>Mucho diseño.<br><i>Mucho rigor.</i></h3><p>'+esc(WILD_320_LAW.statement)+'</p><div class="w320-law-ratio"><b>40%<small>VISUAL</small></b><b>60%<small>TEXTO</small></b><b>100%<small>INTERACCIÓN</small></b></div></div>'+
'<div class="w320-evidence" id="explorar"><div class="w320-section-head"><span>01 · ESTADO</span><h3>Mirar. Entender. Comprobar.</h3></div><div class="w320-evidence-grid">'+wild320Evidence.map(e=>'<button class="w320-evidence-card '+e.tone+'" data-status="'+e.id+'"><b>'+e.label+'</b><span>'+e.short+'</span><i>ABRIR CAPA ↗</i></button>').join("")+'</div><div class="w320-result" id="w320-result" aria-live="polite"><b>ELIGE UN ESTADO</b><span>La interfaz se adapta a tu pregunta.</span></div></div>'+
'<div class="w320-territory" id="territorio"><div class="w320-section-head"><span>02 · TERRITORIO</span><h3>Cuatro ambientes. Una sola historia.</h3></div><div class="w320-territory-grid">'+wild320Territories.map((t,i)=>'<button class="w320-territory-card '+(i===0?"active":"")+'" data-territory="'+t.id+'"><img src="'+t.asset+'" alt="" loading="lazy"><div><b>'+t.name+'</b><span>'+t.subtitle+'</span></div></button>').join("")+'</div><article class="w320-territory-detail" id="w320-territory-detail"><img src="'+wild320Territories[0].asset+'" alt="" loading="lazy"><div><span>RÍO NEUQUÉN</span><h4>Agua que conecta.</h4><p>'+wild320Territories[0].text+'</p></div></article></div>'+
'<div class="w320-orbit"><div class="w320-section-head"><span>03 · SISTEMA</span><h3>La parte que no se ve.</h3></div><div class="w320-orbit-layout"><div class="w320-orbit-visual"><span class="orbit-ring r1"></span><span class="orbit-ring r2"></span><span class="orbit-core">WILD<br>3.20</span><span class="orbit-node n1">FUENTE</span><span class="orbit-node n2">EVIDENCIA</span><span class="orbit-node n3">REGISTRO</span><span class="orbit-node n4">REVISIÓN</span></div><div class="w320-orbit-copy"><p><b>FUENTE → RECURSO → EVIDENCIA → REGISTRO → REVISIÓN</b></p><p>La interfaz muestra el resultado. El motor conserva las relaciones necesarias para saber de dónde salió cada cosa, qué escala tiene y qué todavía falta.</p><div class="w320-metrics"><span><b>'+records.length+'</b> catálogo base</span><span><b>'+inventoryRecords.length+'</b> registros de investigación</span><span><b>'+regionalReferencePool.length+'</b> referencias regionales</span><span><b>'+wild320Sources.length+'</b> fuentes integradas</span></div></div></div></div>'+
'<div class="w320-sources"><div class="w320-section-head"><span>04 · FUENTES DENTRO DEL PROYECTO</span><h3>No te sacamos afuera.</h3></div><p class="w320-source-lead">Cada fuente se transforma en contexto, crédito y criterio visible. La navegación principal termina aquí.</p><div class="w320-source-grid">'+wild320Sources.map(s=>'<article class="w320-source"><div class="w320-source-top"><span>'+esc(s.kind)+'</span><b>'+esc(s.scale)+'</b></div><h4>'+esc(s.title)+'</h4><p>'+esc(s.summary)+'</p><footer><span>'+esc(s.credit)+'</span><span>'+esc(s.date)+'</span><strong>'+esc(s.status)+'</strong></footer></article>').join("")+'</div></div>'+
'<div class="w320-principles"><div class="w320-section-head"><span>05 · NORTE</span><h3>La regla mundial de OCARINA WILD.</h3></div><div class="w320-principles-grid">'+wild320Principles.map(p=>'<article><span>'+p.n+'</span><h4>'+esc(p.title)+'</h4><p>'+esc(p.text)+'</p></article>').join("")+'</div></div>'+
'<div class="w320-final"><span>OCARINA WILD · SAN PATRICIO DEL CHAÑAR</span><h3>Mucho sistema.<br><i>Pocas cosas que hacer.</i></h3><p>Explorar · tocar · descubrir · comprobar.</p></div>';
document.querySelector("footer")?.before(root)||document.body.append(root);
/* REPARADOR 3.20: una sola navegación pública, con profundidad progresiva. */
const north=document.createElement("div"); north.className="w320-northbar"; north.innerHTML='<span>OCARINA WILD · '+WILD_320_VERSION+'</span><b>NORTE MUNDIAL · TODO DENTRO DEL PROYECTO</b><span>CHAÑAR · 2026</span>'; root.prepend(north);
const modes=document.createElement("div"); modes.className="w320-modebar"; modes.setAttribute("role","tablist"); modes.setAttribute("aria-label","Modos de la experiencia"); modes.innerHTML='<button class="active" data-mode="todo" role="tab" aria-selected="true">TODO</button><button data-mode="explorar" role="tab" aria-selected="false">EXPLORAR</button><button data-mode="territorio" role="tab" aria-selected="false">TERRITORIO</button><button data-mode="sistema" role="tab" aria-selected="false">SISTEMA</button><button data-mode="fuentes" role="tab" aria-selected="false">FUENTES</button><button data-mode="norte" role="tab" aria-selected="false">NORTE</button>'; north.after(modes);
const modeMap={todo:[".w320-intro",".w320-evidence",".w320-territory",".w320-orbit",".w320-sources",".w320-principles",".w320-final"],explorar:[".w320-intro",".w320-evidence",".w320-territory",".w320-final"],territorio:[".w320-territory",".w320-final"],sistema:[".w320-orbit",".w320-final"],fuentes:[".w320-sources",".w320-final"],norte:[".w320-principles",".w320-final"]};
const applyMode=mode=>{const keep=modeMap[mode]||modeMap.todo; root.querySelectorAll(".w320-intro,.w320-evidence,.w320-territory,.w320-orbit,.w320-sources,.w320-principles,.w320-final").forEach(x=>x.hidden=!keep.includes("."+x.className.split(" ")[0])); modes.querySelectorAll("button").forEach(b=>{const on=b.dataset.mode===mode;b.classList.toggle("active",on);b.setAttribute("aria-selected",on?"true":"false")}); root.scrollIntoView({behavior:"smooth",block:"start"});};
modes.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>applyMode(b.dataset.mode)));
const sourceDialog=document.createElement("dialog"); sourceDialog.className="w320-source-dialog"; sourceDialog.innerHTML='<button type="button" class="w320-dialog-close" aria-label="Cerrar">×</button><div class="w320-dialog-body"></div>'; root.append(sourceDialog);
const sourceBody=sourceDialog.querySelector(".w320-dialog-body"); sourceDialog.querySelector(".w320-dialog-close").addEventListener("click",()=>sourceDialog.close());
root.querySelectorAll(".w320-source").forEach(card=>{card.setAttribute("tabindex","0");card.setAttribute("role","button");const open=()=>{const title=card.querySelector("h4")?.textContent||"Fuente";const summary=card.querySelector("p")?.textContent||"";const foot=[...card.querySelectorAll("footer span,footer strong")].map(x=>x.textContent).join(" · ");sourceBody.innerHTML="<span>FICHA DE FUENTE · CONTEXTUALIZADA</span><h3>"+esc(title)+"</h3><p>"+esc(summary)+"</p><div class=\"w320-dialog-credit\">"+esc(foot)+"</div><p class=\"w320-dialog-note\">La fuente aporta respaldo y contexto; la afirmación pública se conserva dentro de OCARINA WILD con su escala y estado. Este panel no te obliga a salir del proyecto.</p>";sourceDialog.showModal()};card.addEventListener("click",open);card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open()}})});
root.querySelectorAll("[data-jump]").forEach(b=>b.addEventListener("click",()=>root.querySelector("#"+b.dataset.jump)?.scrollIntoView({behavior:"smooth",block:"start"})));
const result=root.querySelector("#w320-result"),copy={documentado:"Hay evidencia local o un evento concreto documentado. La afirmación se mantiene acotada a lo que realmente permite la fuente.",referencia:"La información sirve como referencia para investigar. No se convierte en presencia local por distribución o semejanza.",pendiente:"La pregunta queda abierta. OCARINA WILD conserva el vacío en lugar de inventar una respuesta."};
root.querySelectorAll("[data-status]").forEach(b=>b.addEventListener("click",()=>{root.querySelectorAll("[data-status]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");result.innerHTML="<b>"+b.querySelector("b").textContent+"</b><span>"+copy[b.dataset.status]+"</span>"}));
const detail=root.querySelector("#w320-territory-detail");root.querySelectorAll("[data-territory]").forEach(b=>b.addEventListener("click",()=>{const t=wild320Territories.find(x=>x.id===b.dataset.territory);root.querySelectorAll("[data-territory]").forEach(x=>x.classList.remove("active"));b.classList.add("active");detail.innerHTML='<img src="'+t.asset+'" alt="" loading="lazy"><div><span>'+t.name+'</span><h4>'+t.subtitle+'.</h4><p>'+t.text+'</p></div>'}));
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();